# Generated by Django 5.2.8 on 2025-11-28 03:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField(default=0.0)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Option",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(blank=True, max_length=1000)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="options/"),
                ),
                ("is_correct", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Passage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                (
                    "text",
                    models.TextField(
                        help_text="Content of the passage (LaTeX supported)"
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="passages/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(help_text="Question text (LaTeX supported)")),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="questions/"),
                ),
                ("marks", models.FloatField(default=4.0)),
                ("negative_marks", models.FloatField(default=1.0)),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("MCQ_SINGLE", "Single Correct MCQ"),
                            ("MCQ_MULTI", "Multi Correct MCQ"),
                            ("NUMERICAL", "Numerical"),
                            ("MATRIX", "Matrix Match"),
                            ("TRUE_FALSE", "True/False"),
                        ],
                        max_length=20,
                    ),
                ),
                ("numerical_answer", models.FloatField(blank=True, null=True)),
                (
                    "numerical_tolerance",
                    models.FloatField(default=0.0, help_text="Allowed range (+/-)"),
                ),
                (
                    "matrix_config",
                    models.JSONField(
                        blank=True,
                        help_text="JSON configuration for Matrix Match",
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("time_limit_minutes", models.IntegerField(default=60)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Response",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer_data", models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
