# Generated by Django 5.2.8 on 2025-11-30 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="marks",
        ),
        migrations.RemoveField(
            model_name="question",
            name="negative_marks",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="questions",
        ),
        migrations.AddField(
            model_name="question",
            name="chapter",
            field=models.CharField(
                blank=True,
                choices=[
                    ("VECTORS", "Vectors"),
                    ("KINEMATICS_1D", "Kinematics - 1D"),
                    ("KINEMATICS_2D", "Kinematics - 2D"),
                    ("NEWTONS_LAWS", "Newton's Laws of Motion"),
                    ("FRICTION", "Friction"),
                    ("CIRCULAR_MOTION", "Circular Motion"),
                    ("WORK_POWER_ENERGY", "Work, Power and Energy"),
                    (
                        "COM_MOMENTUM",
                        "Center of Mass and Conservation of Linear Momentum",
                    ),
                    ("ROTATIONAL_MOTION", "Rotational Motion"),
                    ("GRAVITATION", "Gravitation"),
                    ("FLUID_DYNAMICS", "Fluid Dynamics"),
                    ("MECHANICAL_PROPERTIES", "Mechanical Properties of Matter"),
                    ("SHM", "Simple Harmonic Motion"),
                    ("WAVE_MOTION", "Wave Motion"),
                    ("HEAT_THERMODYNAMICS", "Heat and Thermodynamics"),
                    ("ELECTROSTATICS", "Electrostatics"),
                    ("CURRENT_ELECTRICITY", "Current Electricity"),
                    ("CAPACITANCE", "Capacitance"),
                    ("MAGNETISM", "Magnetism"),
                    ("EMI", "Electromagnetic Induction"),
                    ("AC", "Alternating Current"),
                    ("GEOMETRICAL_OPTICS", "Geometrical Optics"),
                    ("WAVE_OPTICS", "Wave Optics"),
                    ("MODERN_PHYSICS", "Modern Physics"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("VERY_EASY", "Very Easy"),
                    ("EASY", "Easy"),
                    ("MODERATE", "Moderate"),
                    ("DIFFICULT", "Difficult"),
                    ("VERY_DIFFICULT", "Very Difficult"),
                ],
                default="MODERATE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="subtopic",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name="QuizQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marks", models.FloatField(default=4.0)),
                ("negative_marks", models.FloatField(default=1.0)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="quiz.question"
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="quiz.quiz"
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
