# Generated by Django 5.2.8 on 2025-11-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0003_remove_question_marks_remove_question_negative_marks_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="questions",
            field=models.ManyToManyField(
                through="quiz.QuizQuestion", to="quiz.question"
            ),
        ),
    ]
