# Generated by Django 5.2.8 on 2025-12-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0004_quiz_questions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("MCQ_SINGLE", "Single Correct MCQ"),
                    ("MCQ_MULTI", "Multi Correct MCQ"),
                    ("NUMERICAL", "Numerical"),
                    ("MATRIX", "Matrix Match"),
                    ("MATRIX_SINGLE", "Matrix Single"),
                    ("TRUE_FALSE", "True/False"),
                ],
                max_length=20,
            ),
        ),
    ]
