# Generated by Django 5.2.8 on 2025-12-06 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0005_alter_question_question_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="matrix_config",
            field=models.JSONField(
                blank=True,
                help_text="DEPRECATED: Use MatrixRow/MatrixCol models instead",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="MatrixCol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(help_text="e.g. p, q, r", max_length=10)),
                ("text", models.CharField(blank=True, max_length=1000)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="matrix_cols/"),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matrix_cols",
                        to="quiz.question",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MatrixRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(help_text="e.g. A, B, C", max_length=10)),
                ("text", models.CharField(blank=True, max_length=1000)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="matrix_rows/"),
                ),
                (
                    "matches",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated IDs of correct columns (e.g. p,q)",
                        max_length=50,
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matrix_rows",
                        to="quiz.question",
                    ),
                ),
            ],
        ),
    ]
