# Generated by Django 5.2.8 on 2025-12-16 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("quiz", "0006_alter_question_matrix_config_matrixcol_matrixrow"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="assigned_groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="Batches/Groups this quiz is assigned to",
                related_name="quizzes",
                to="auth.group",
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="assigned_students",
            field=models.ManyToManyField(
                blank=True,
                help_text="Individual students this quiz is assigned to",
                related_name="assigned_quizzes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="passages",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select passages to add all their questions to the quiz automatically.",
                to="quiz.passage",
            ),
        ),
        migrations.CreateModel(
            name="SolutionBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        blank=True, help_text="Text content (LaTeX supported)"
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="solutions/"),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solution_blocks",
                        to="quiz.question",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
