# Generated by Django 5.2.8 on 2025-12-19 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0007_quiz_assigned_groups_quiz_assigned_students_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="assertion",
            field=models.TextField(
                blank=True,
                help_text="Assertion text (for Assertion-Reason questions)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="reason",
            field=models.TextField(
                blank=True,
                help_text="Reason text (for Assertion-Reason questions)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("MCQ_SINGLE", "Single Correct MCQ"),
                    ("MCQ_MULTI", "Multi Correct MCQ"),
                    ("NUMERICAL", "Numerical"),
                    ("MATRIX", "Matrix Match"),
                    ("MATRIX_SINGLE", "Matrix Single"),
                    ("TRUE_FALSE", "True/False"),
                    ("ASSERTION_REASON", "Assertion-Reason"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="text",
            field=models.TextField(
                blank=True, help_text="Question text (LaTeX supported)"
            ),
        ),
    ]
