# Generated by Django 5.2.8 on 2025-12-19 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0008_question_assertion_question_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="allow_partial_marking",
            field=models.BooleanField(
                default=True,
                help_text="For MCQ Multi: If true, partial marks are awarded. If false, only full marks or negative marks.",
            ),
        ),
    ]
