# Generated by Django 5.2.8 on 2025-12-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0009_question_allow_partial_marking"),
    ]

    operations = [
        migrations.AddField(
            model_name="response",
            name="status",
            field=models.CharField(
                choices=[
                    ("NOT_VISITED", "Not Visited"),
                    ("NOT_ANSWERED", "Not Answered"),
                    ("ANSWERED", "Answered"),
                    ("MARKED_FOR_REVIEW", "Marked for Review"),
                    ("ANSWERED_MARKED", "Answered & Marked for Review"),
                ],
                default="NOT_VISITED",
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="response",
            unique_together={("attempt", "question")},
        ),
    ]
