# Generated by Django 5.2.8 on 2025-12-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0010_response_status_alter_response_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="is_public",
            field=models.BooleanField(
                default=False,
                help_text="If true, visible to everyone; otherwise only assigned students/groups.",
            ),
        ),
    ]
